struct Constants {
    static let checkPermission = "checkPermission"
    static let blackListedWords = [
                            "valid",
                            "doll",
                            "through",
                            "thru",
                            "valid thru",
                            "alid thru",
                            "alid thr",
                            "thrd",
                            "valid through",
                            "from",
                            "valid from",
                            "alid from",
                            "alid fro",
                            "international",
                            "rupay",
                            "meal",
                            "pass",
                            "meal pass",
                            "debit",
                            "debit card",
                            "visa",
                            "mastercard",
                            "platinum",
                            "axis",
                            "sbi",
                            "axis bank",
                            "credit",
                            "card",
                            "boi",
                            "titanium",
                            "bank",
                            "global",
                            "state bank",
                            "of",
                            "the",
                            "india",
                            "valid only",
                            "classic",
                            "gold",
                            "sbi card",
                            "visa classic",
                            "visa signature",
                            "visa gold",
                            "electronic",
                            "use only",
                            "electronic use only",
                            "only",
                            "use",
                            "expires",
                            "end",
                            "expires end",
                            "valid till",
                            "expire date",
                            "date",
                            "expiry",
                            "expiry date",
                            "premier",
                            "world",
                            "uk",
                            "hsbc",
                            "cvv",
                            "cvc",
                            "more",
                            "amex",
                            "valid from valid thru",
                            "valid from valid till",
                            "member since",
                            "prepaid",
                            "visa"
    ]
}

extension String {
   var isNumeric: Bool {
     return !(self.isEmpty) && self.allSatisfy { $0.isNumber }
   }
}
